# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:


- task: TerraformInstaller@0
  displayName: Install Terraform v1.2.3
  inputs:
    terraformversion: '1.2.3'

- task: TerraformTaskV1@1
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    

- task: TerraformTaskV1@2
  displayName: terraofrm plan -out=main.tfplan
  inputs:
    provider: 'azurerm'
    command: plan
    commandOptions: '-out=main.tfplan'


- task: TerraformTaskV1@3
  displayName: terraform apply main.tfplan
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: main.tfplan
    

